import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>

          <Link href="/blog">
            <li>Blog</li>
          </Link>
          <Link href="/contact">
            <li>Contact</li>
          </Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <div className="heading">
          <h1>Hunter Coder</h1>
          <h5>A Blog for hunting coder by hunting coder</h5>
        </div>
        <div className="sub-heading">
          <h3>Popular blogs</h3>
        </div>
        <div className={styles.description}>
          <div className="blog">
            <div className="blog-item">
              <h2>How to learn Javascript in 2022</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Officia aliquid impedit alias illum esse assumenda odit! Odio
                saepe repellat non?
              </p>
            </div>
            <div className="blog-item">
              <h2>How to learn Javascript in 2022</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Officia aliquid impedit alias illum esse assumenda odit! Odio
                saepe repellat non?
              </p>
            </div>
            <div className="blog-item">
              <h2>How to learn Javascript in 2022</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Officia aliquid impedit alias illum esse assumenda odit! Odio
                saepe repellat non?
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
